name: Build

on:
  push:

  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  QT_VERSION: '6.9.0'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Install Qt
        id: qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          add-tools-to-path: true
          cache: true

      - name: Generate and Build with CMake
        shell: pwsh
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build . --config Release 
          cmake --install . --config Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QuickSoundSwitcher_msvc_64
          path: build/install

      - name: Get latest Git tag and bump version
        id: get_version
        shell: bash
        run: |
          git fetch --tags  # Fetch all tags
          # Get the latest tag sorted by version, falling back to "0" if none exist
          TAG=$(git tag --sort=-v:refname | head -n 1 || echo "0")
          # Extract the numeric part of the tag
          VERSION_NUM=$(echo $TAG | grep -o '[0-9]\+' | tail -n 1)
          # Increment the version number
          NEXT_VERSION=$((VERSION_NUM + 1))
          echo "New version: $NEXT_VERSION"
          echo "TagVersion=${NEXT_VERSION}" >> $GITHUB_ENV

      - name: Update .iss version
        shell: pwsh
        run: |
          # Use the version number calculated in the previous step
          $content = Get-Content tools/installer.iss
          $new = $content -replace '(?<=#define AppVersion ")[^"]+', "${{ env.TagVersion }}"
          Set-Content tools/installer.iss -Value $new

      - name: Create Installer 
        shell: pwsh
        run: |
          $env:Path += ";${env:ProgramFiles(x86)}\Inno Setup 6"
          iscc.exe tools/installer.iss

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: QuickSoundSwitcher_Installer
          path: tools/Output/QuickSoundSwitcher_Installer.exe